# frozen_string_literal: true

require 'minitest/test_task'
require 'rspec/core/rake_task'
require 'rubocop/rake_task'

RuboCop::RakeTask.new(:rubocop)

Minitest::TestTask.create :test_all do |t|
  t.test_globs = Dir['test/**/test_*.rb']
  t.libs << 'test'
  t.verbose = false
end

RSpec::Core::RakeTask.new(:spec) do |t|
  t.verbose = false
end

task test: %i[spec test_all]

task :gem do
  sh('gem build *.gemspec')
end

task default: %i[test rubocop]
