source "http://rubygems.org"

gemspec

gem 'albino'
gem 'bluecloth'
gem 'builder'
gem 'coderay'
gem 'coffee-script'
gem 'erubis'
gem 'haml'
gem 'kramdown'
gem 'less', '~> 2.0'
gem 'markaby'
gem 'maruku'
gem 'mime-types'
gem 'mustache'
gem 'nokogiri'
gem 'rack'
gem 'rainpress'
gem 'rdiscount'
gem 'rdoc'
gem 'redcarpet'
gem 'RedCloth'
gem 'rubypants'
gem 'sass', '~> 3.1'
gem 'slim'
gem 'systemu'
gem 'typogruby'
gem 'uglifier'
gem 'w3c_validators'
gem 'yuicompressor'
