source "http://rubygems.org"

gemspec

gem 'adsf'
gem 'bluecloth'
gem 'builder'
gem 'coderay'
gem 'coffee-script'
gem 'debugger'
gem 'erubis'
gem 'fog'
gem 'haml'
gem 'handlebars'
gem 'kramdown'
gem 'less', '~> 2.0'
gem 'listen'
gem 'markaby'
gem 'maruku'
gem 'mime-types'
gem 'mustache'
gem 'nokogiri', '~> 1.5.5'
gem 'pandoc-ruby'
gem 'pry'
gem 'pygments.rb'
gem 'rack'
gem 'rake'
gem 'rainpress'
gem 'rdiscount'
gem 'rdoc'
gem 'redcarpet'
gem 'RedCloth'
gem 'rubypants'
gem 'sass', '~> 3.2.2'
gem 'slim'
gem 'sqlite3'
gem 'systemu'
gem 'typogruby'
gem 'uglifier'
gem 'w3c_validators'
gem 'yuicompressor'

# disabled until colorize/colored issue is fixed
#gem 'coveralls', :require => false
