require_relative 'views/mixins/document'
require_relative 'views/mixins/mutable_document'

require_relative 'views/config'
require_relative 'views/identifiable_collection'
require_relative 'views/item'
require_relative 'views/item_collection'
require_relative 'views/item_rep'
require_relative 'views/item_rep_collection'
require_relative 'views/layout'
require_relative 'views/layout_collection'
require_relative 'views/mutable_config'
require_relative 'views/mutable_identifiable_collection'
require_relative 'views/mutable_item'
require_relative 'views/mutable_item_collection'
require_relative 'views/mutable_layout'
require_relative 'views/mutable_layout_collection'
require_relative 'views/site'
