# encoding: utf-8

module Nanoc::Filters
end

require 'nanoc/filters/asciidoc'
require 'nanoc/filters/bluecloth'
require 'nanoc/filters/colorize_syntax'
require 'nanoc/filters/coffeescript'
require 'nanoc/filters/erb'
require 'nanoc/filters/erubis'
require 'nanoc/filters/haml'
require 'nanoc/filters/handlebars'
require 'nanoc/filters/kramdown'
require 'nanoc/filters/less'
require 'nanoc/filters/maruku'
require 'nanoc/filters/mustache'
require 'nanoc/filters/pandoc'
require 'nanoc/filters/rainpress'
require 'nanoc/filters/rdiscount'
require 'nanoc/filters/rdoc'
require 'nanoc/filters/redcarpet'
require 'nanoc/filters/redcloth'
require 'nanoc/filters/relativize_paths'
require 'nanoc/filters/rubypants'
require 'nanoc/filters/sass'
require 'nanoc/filters/slim'
require 'nanoc/filters/typogruby'
require 'nanoc/filters/uglify_js'
require 'nanoc/filters/xsl'
require 'nanoc/filters/yui_compressor'
