# frozen_string_literal: true

require 'rake/testtask'
require 'rspec/core/rake_task'
require 'rubocop/rake_task'

RuboCop::RakeTask.new(:rubocop)

RSpec::Core::RakeTask.new(:spec) do |t|
  t.verbose = false
end

Rake::TestTask.new(:test_all) do |t|
  t.test_files = Dir['test/**/test_*.rb']
  t.libs << 'test'
  t.verbose = false
end

task test: %i[spec test_all]

task :gem do
  sh('gem build *.gemspec')
end

task default: %i[test rubocop]
