# encoding: utf-8

desc 'Remove output files generated by nanoc'
task :clean do
  # Load site
  site = Nanoc::Site.new('.')
  if site.nil?
    $stderr.puts 'The current working directory does not seem to be a ' +
                 'valid/complete nanoc site directory; aborting.'
    exit 1
  end

  # Clean
  clean = ::Nanoc::Tasks::Clean.new(site)
  clean.run
end
